import { parseAbi } from "viem";

export const accessHubAbi = parseAbi([
  "function timelock() view returns (address)",
  "function treasury() view returns (address)",
  "function voteModule() view returns (address)",
  "function voter() view returns (address)",
  "function minter() view returns (address)",
  "function xRam() view returns (address)",
  "function r33() view returns (address)",
  "function nfpManager() view returns (address)",
  "function ramsesV3PoolFactory() view returns (address)",
  "function poolFactory() view returns (address)",
  "function feeCollector() view returns (address)",
  "function clGaugeFactory() view returns (address)",
  "function gaugeFactory() view returns (address)",
  "function feeDistributorFactory() view returns (address)",
  "function feeRecipientFactory() view returns (address)",
  "function initialize((address timelock, address treasury, address voter, address minter, address xRam, address r33, address ramsesV3PoolFactory, address poolFactory, address clGaugeFactory, address gaugeFactory, address feeRecipientFactory, address feeDistributorFactory, address feeCollector, address voteModule) params)",
  "function reinit((address timelock, address treasury, address voter, address minter, address xRam, address r33, address ramsesV3PoolFactory, address poolFactory, address clGaugeFactory, address gaugeFactory, address feeRecipientFactory, address feeDistributorFactory, address feeCollector, address voteModule) params)",
  "function initializeVoter((address ram, address legacyFactory, address gauges, address feeDistributorFactory, address minter, address msig, address xRam, address clFactory, address clGaugeFactory, address nfpManager, address feeRecipientFactory, address voteModule) inputs)",
  "function setSwapFees(address[] _pools, uint24[] _swapFees)",
  "function setFeeSplitCL(address[] _pools, uint24[] _feeProtocol)",
  "function setFeeSplitLegacy(address[] _pools, uint256[] _feeSplits)",
  "function setFeeRecipientLegacyBatched(address[] _pairs, address[] _feeRecipients)",
  "function setNewGovernorInVoter(address _newGovernor)",
  "function governanceWhitelist(address[] _token, bool[] _whitelisted)",
  "function killGauge(address[] _pairs)",
  "function reviveGauge(address[] _pairs)",
  "function setEmissionsRatioInVoter(uint256 _pct)",
  "function retrieveStuckEmissionsToGovernance(address _gauge, uint256 _period)",
  "function setTimeThresholdForRewarder(uint256 _timeThreshold)",
  "function createLegacyGauge(address _pool) returns (address)",
  "function createCLGauge(address tokenA, address tokenB, int24 tickSpacing) returns (address)",
  "function setFeeCollectorAccessHub(address _feeCollector)",
  "function setFeeCollectorInClGaugeFactory(address _feeCollector)",
  "function transferWhitelistInXRam(address[] _who, bool[] _whitelisted)",
  "function transferToWhitelistInXRam(address[] _who, bool[] _whitelisted)",
  "function rescueR33Token(address _token)",
  "function transferOperatorInR33(address _newOperator)",
  "function unwrapR33LegacyIncentives(address _lpToken)",
  "function whitelistAggregatorInR33(address _aggregator, bool _status)",
  "function adjustEmissionsInMinter(int256 _basisPointsChange)",
  "function removeFeeDistributorRewards(address[] _pools, address[] _rewards)",
  "function setTreasuryInFeeCollector(address newTreasury)",
  "function setTreasuryFeesInFeeCollector(uint256 _treasuryFees)",
  "function setFeeToTreasuryInFeeRecipientFactory(uint256 _feeToTreasury)",
  "function setTreasuryInFeeRecipientFactory(address _treasury)",
  "function enableTickSpacing(int24 tickSpacing, uint24 initialFee)",
  "function setGlobalClFeeProtocol(uint24 _feeProtocolGlobal)",
  "function setVoterAddressInFactoryV3(address _voter)",
  "function setFeeCollectorInFactoryV3(address _newFeeCollector)",
  "function updateFeeDistributorForGauge(address _gauge, address _newFeeDistributor)",
  "function createFeeDistributorWithRecipient(address _feeRecipient) returns (address)",
  "function setTreasuryInLegacyFactory(address _treasury)",
  "function setVoterInLegacyFactory(address _voter)",
  "function setFeeSplitWhenNoGauge(bool status)",
  "function setLegacyFeeSplitGlobal(uint256 _feeSplit)",
  "function setLegacyFeeGlobal(uint256 _fee)",
  "function setSkimEnabledLegacy(address _pair, bool _status)",
  "function setCooldownExemption(address[] _candidates, bool[] _exempt)",
  "function setNewVoteModuleCooldown(uint256 _newCooldown)",
  "function setVoterInFeeRecipientFactory(address _voter)",
  "function execute(address _target, bytes _payload)",
  "function setNewTimelock(address _timelock)",
  "function compoundR33()",
  "function clawbackIncentives(address _tokenToClawback, address _poolAddress)",
  "function toggleAntiSybil()",
  "function transferOperatorInXRam(address _operator)",
  "function setRewardValidator(address _rewardValidator)",
  "function setNfpManager(address _nfpManager)",
  "function setClGaugeFactoryImpl(address _clGaugeFactory)",
  "function addAuthorizedClaimerVoter(address _claimer)",
  "function removeAuthorizedClaimerVoter(address _claimer)",
  "function syncClGaugesBatch(uint256 startIndex, uint256 endIndex)",
  "function addRewardsToGauge(address _gauge, address _reward)",
  "function removeRewardsFromGauge(address _gauge, address _reward)",
  "function batchAddRewardsToGauges(address[] _gauges, address[] _rewards)",
  "function batchRemoveRewardsFromGauges(address[] _gauges, address[] _rewards)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function PROTOCOL_OPERATOR() view returns (bytes32)",
  "function SWAP_FEE_SETTER() view returns (bytes32)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function getRoleMember(bytes32 role, uint256 index) view returns (address)",
  "function getRoleMemberCount(bytes32 role) view returns (uint256)",
  "function getRoleMembers(bytes32 role) view returns (address[])",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeRole(bytes32 role, address account)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)"
]);
