import { parseAbi } from "viem";

export const dlmmPoolAbi = parseAbi([
  "function approveForAll(address spender, bool approved)",
  "function balanceOf(address account, uint256 id) view returns (uint256)",
  "function balanceOfBatch(address[] accounts, uint256[] ids) view returns (uint256[])",
  "function batchTransferFrom(address from, address to, uint256[] ids, uint256[] amounts)",
  "function burn(address from, address to, uint256[] ids, uint256[] amountsToBurn) returns (bytes32[])",
  "function collectProtocolFees() returns (bytes32)",
  "function flashLoan(address receiver, bytes32 amounts, bytes data)",
  "function forceDecay()",
  "function getActiveId() view returns (uint24)",
  "function getBin(uint24 id) view returns (uint128, uint128)",
  "function getBinStep() pure returns (uint16)",
  "function getFactory() view returns (address)",
  "function getIdFromPrice(uint256 price) pure returns (uint24)",
  "function getLBHooksParameters() view returns (bytes32)",
  "function getNextNonEmptyBin(bool swapForY, uint24 id) view returns (uint24)",
  "function getOracleParameters() view returns (uint8, uint16, uint16, uint40, uint40)",
  "function getOracleSampleAt(uint40 lookupTimestamp) view returns (uint64, uint64, uint64)",
  "function getPriceFromId(uint24 id) pure returns (uint256)",
  "function getProtocolFees() view returns (uint128, uint128)",
  "function getReserves() view returns (uint128, uint128)",
  "function getStaticFeeParameters() view returns (uint16, uint16, uint16, uint16, uint24, uint16, uint24)",
  "function getSwapIn(uint128 amountOut, bool swapForY) view returns (uint128, uint128, uint128)",
  "function getSwapOut(uint128 amountIn, bool swapForY) view returns (uint128, uint128, uint128)",
  "function getTokenX() pure returns (address)",
  "function getTokenY() pure returns (address)",
  "function getVariableFeeParameters() view returns (uint24, uint24, uint24, uint40)",
  "function implementation() view returns (address)",
  "function increaseOracleLength(uint16 newLength)",
  "function initialize(uint16 baseFactor, uint16 filterPeriod, uint16 decayPeriod, uint16 reductionFactor, uint24 variableFeeControl, uint16 protocolShare, uint24 maxVolatilityAccumulator, uint24 activeId)",
  "function isApprovedForAll(address owner, address spender) view returns (bool)",
  "function mint(address to, bytes32[] liquidityConfigs, address refundTo) returns (bytes32, bytes32, uint256[])",
  "function name() view returns (string)",
  "function setHooksParameters(bytes32 hooksParameters, bytes onHooksSetData)",
  "function setStaticFeeParameters(uint16 baseFactor, uint16 filterPeriod, uint16 decayPeriod, uint16 reductionFactor, uint24 variableFeeControl, uint16 protocolShare, uint24 maxVolatilityAccumulator)",
  "function swap(bool swapForY, address to) returns (bytes32)",
  "function symbol() view returns (string)",
  "function totalSupply(uint256 id) view returns (uint256)"
]);
