import { parseAbi } from "viem";

export const dlmmFactoryAbi = parseAbi([
  "error LBFactory__PresetIsLockedForUsers(address user, uint256 binStep)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function DEFAULT_PROTOCOL_SHARE() view returns (uint16)",
  "function GAUGED_PROTOCOL_SHARE() view returns (uint16)",
  "function LB_HOOKS_MANAGER_ROLE() view returns (bytes32)",
  "function acceptOwnership()",
  "function addQuoteAsset(address quoteAsset)",
  "function createLBPair(address tokenX, address tokenY, uint24 activeId, uint16 binStep) returns (address)",
  "function defaultProtocolShare() pure returns (uint16)",
  "function feeCollector() view returns (address)",
  "function forceDecay(address pair)",
  "function gaugedProtocolShare() pure returns (uint16)",
  "function getAllBinSteps() view returns (uint256[])",
  "function getAllLBPairs(address tokenX, address tokenY) view returns ((uint16 binStep, address LBPair, bool createdByOwner, bool ignoredForRouting)[])",
  "function getFeeRecipient() view returns (address)",
  "function getFlashLoanFee() view returns (uint256)",
  "function getLBPairAtIndex(uint256 index) view returns (address)",
  "function getLBPairImplementation() view returns (address)",
  "function getLBPairInformation(address tokenA, address tokenB, uint256 binStep) view returns ((uint16 binStep, address LBPair, bool createdByOwner, bool ignoredForRouting))",
  "function getMaxFlashLoanFee() pure returns (uint256)",
  "function getMinBinStep() pure returns (uint256)",
  "function getNumberOfLBPairs() view returns (uint256)",
  "function getNumberOfQuoteAssets() view returns (uint256)",
  "function getOpenBinSteps() view returns (uint256[])",
  "function getPreset(uint256 binStep) view returns (uint256, uint256, uint256, uint256, uint256, uint256, uint256, bool)",
  "function getQuoteAssetAtIndex(uint256 index) view returns (address)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function isPool(address pool) view returns (bool)",
  "function isQuoteAsset(address token) view returns (bool)",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function removeLBHooksOnPair(address tokenX, address tokenY, uint16 binStep)",
  "function removePreset(uint16 binStep)",
  "function removeQuoteAsset(address quoteAsset)",
  "function renounceOwnership()",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeRole(bytes32 role, address account)",
  "function setFeeRecipient(address feeRecipient)",
  "function setFeesParametersOnPair(address tokenX, address tokenY, uint16 binStep, uint16 baseFactor, uint16 filterPeriod, uint16 decayPeriod, uint16 reductionFactor, uint24 variableFeeControl, uint16 protocolShare, uint24 maxVolatilityAccumulator)",
  "function setFlashLoanFee(uint256 flashLoanFee)",
  "function setLBHooksParametersOnPair(address tokenX, address tokenY, uint16 binStep, bytes32 hooksParameters, bytes onHooksSetData)",
  "function setLBPairIgnored(address tokenX, address tokenY, uint16 binStep, bool ignored)",
  "function setLBPairImplementation(address newLBPairImplementation)",
  "function setPoolDefaultProtocolShare(address pool)",
  "function setPoolGaugedProtocolShare(address pool)",
  "function setPoolProtocolShare(address pool, uint16 protocolShare)",
  "function setPreset(uint16 binStep, uint16 baseFactor, uint16 filterPeriod, uint16 decayPeriod, uint16 reductionFactor, uint24 variableFeeControl, uint16 protocolShare, uint24 maxVolatilityAccumulator, bool isOpen)",
  "function setPresetOpenState(uint16 binStep, bool isOpen)",
  "function setPresetProtocolShare(uint16 binStep, uint16 protocolShare)",
  "function setVoter(address newVoter)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function transferOwnership(address newOwner)",
  "function voter() view returns (address)"
]);
