import { parseAbi } from "viem";

export const legacyPairAbi = parseAbi([
  "function MINIMUM_LIQUIDITY() view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address to, uint256 value) returns (bool)",
  "function transferFrom(address from, address to, uint256 value) returns (bool)",
  "function factory() view returns (address)",
  "function fee() view returns (uint256)",
  "function feeRecipient() view returns (address)",
  "function feeSplit() view returns (uint256)",
  "function getAmountOut(uint256 amountIn, address tokenIn) view returns (uint256 amountOut)",
  "function getReserves() view returns (uint112 _reserve0, uint112 _reserve1, uint32 _blockTimestampLast)",
  "function kLast() view returns (uint256)",
  "function metadata() view returns (uint256 _decimals0, uint256 _decimals1, uint256 _reserve0, uint256 _reserve1, bool _stable, address _token0, address _token1)",
  "function name() view returns (string)",
  "function observationLength() view returns (uint256)",
  "function observations(uint256) view returns (uint256 timestamp, uint256 reserve0Cumulative, uint256 reserve1Cumulative)",
  "function lastObservation() view returns ((uint256 timestamp, uint256 reserve0Cumulative, uint256 reserve1Cumulative))",
  "function currentCumulativePrices() view returns (uint256 reserve0Cumulative, uint256 reserve1Cumulative, uint256 blockTimestamp)",
  "function current(address tokenIn, uint256 amountIn) view returns (uint256 amountOut)",
  "function quote(address tokenIn, uint256 amountIn, uint256 granularity) view returns (uint256 amountOut)",
  "function prices(address tokenIn, uint256 amountIn, uint256 points) view returns (uint256[])",
  "function sample(address tokenIn, uint256 amountIn, uint256 points, uint256 window) view returns (uint256[])",
  "function reserve0CumulativeLast() view returns (uint256)",
  "function reserve1CumulativeLast() view returns (uint256)",
  "function stable() view returns (bool)",
  "function symbol() view returns (string)",
  "function token0() view returns (address)",
  "function token1() view returns (address)",
  "function initialize(address _token0, address _token1, bool _stable)",
  "function mint(address to) returns (uint256 liquidity)",
  "function burn(address to) returns (uint256 amount0, uint256 amount1)",
  "function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes data)",
  "function skim(address to)",
  "function sync()",
  "function setFeeRecipient(address _pairFees)",
  "function setFeeSplit(uint256 _feeSplit)",
  "function setFee(uint256 _fee)",
  "function mintFee()"
]);
