import { parseAbi } from "viem";

export const treasuryHelperAbi = parseAbi([
  "function USDC() view returns (address)",
  "function initialize(address _accessHub, address _initialOperator, address _legacyRouter)",
  "function updateMember(address _account, uint256 _weight)",
  "function updateOperator(address _newOperator)",
  "function depositXRam(uint256 _amount)",
  "function withdrawXRam(uint256 _amount)",
  "function claimIncentives(address[] _feeDistributors, address[][] _tokens)",
  "function submitVotes(address[] _pools, uint256[] _weights)",
  "function swapIncentiveViaAggregator((address _aggregator, address _tokenIn, address _tokenOut, uint256 _amountIn, uint256 _minAmountOut, bytes _callData) _params)",
  "function tryUnwrapLP(address token)",
  "function whitelistAggregator(address _aggregator, bool _status)",
  "function distribute(address _token)",
  "function getMemberWeight(address _account) view returns (uint256)",
  "function getMemberCount() view returns (uint256)",
  "function getAllMembers() view returns (address[] accounts, uint256[] weights)",
  "function treasuryVotingPower() view returns (uint256)",
  "function recoverERC20(address _token, uint256 _amount)",
  "function recoverNative()",
  "function emergencyExecute(address _to, bytes _data)",
  "function clawBackToTreasury(address _token, uint256 _amount)",
  "function getXRam() view returns (address)",
  "function getVoteModule() view returns (address)",
  "function getTreasury() view returns (address)",
  "function getTimelock() view returns (address)",
  "function getVoter() view returns (address)",
  "function getOperator() view returns (address)",
  "function isAggregatorWhitelisted(address _aggregator) view returns (bool)",
  "function getTotalWeight() view returns (uint256)",
  "function getLegacyRouter() view returns (address)",
  "function getBasisPoints() view returns (uint256)",
  "function getAccessHub() view returns (address)"
]);
